# Generated by Django 2.0 on 2020-09-24 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Event Name')),
                ('tagline', models.TextField(verbose_name='Tagline')),
                ('speaker', models.CharField(max_length=120, verbose_name='Speaker')),
                ('topic', models.TextField(verbose_name='Topic')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('room_capacity', models.IntegerField(verbose_name='Room Capacity')),
                ('current_seat_number', models.IntegerField(default=0, verbose_name='Current Seat Number')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Event Image')),
                ('date', models.DateField(null=True, verbose_name='Date')),
                ('period', models.CharField(choices=[('m', 'Morning'), ('mm', 'Midmorning'), ('a', 'Afternoon')], max_length=50, null=True, verbose_name='Period')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Start Time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='End Time')),
            ],
        ),
        migrations.CreateModel(
            name='EventAttendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(verbose_name='Event Date')),
                ('event_period', models.CharField(choices=[('m', 'Morning'), ('mm', 'Midmorning'), ('a', 'Afternoon')], max_length=50, null=True, verbose_name='Event Period')),
                ('date_registered', models.DateField(verbose_name='Date Registered')),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Attendee')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Event', verbose_name='Event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, through='account.EventAttendee', to=settings.AUTH_USER_MODEL),
        ),
    ]
